"""initial schema

Revision ID: f7bfcca3435c
Revises: 
Create Date: 2026-07-07 15:43:29.042467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7bfcca3435c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_table('cells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('first_use_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_breached', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cells_code'), 'cells', ['code'], unique=True)
    op.create_index(op.f('ix_cells_status'), 'cells', ['status'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('header_detected', sa.Boolean(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_serial_number'), 'instruments', ['serial_number'], unique=True)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_status'), 'schedules', ['status'], unique=False)
    op.create_table('run_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('batch_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_batches_instrument_id'), 'run_batches', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_run_batches_schedule_id'), 'run_batches', ['schedule_id'], unique=False)
    op.create_table('samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('parent_sample', sa.String(length=255), nullable=True),
    sa.Column('sanger_ids', sa.JSON(), nullable=False),
    sa.Column('oplc', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samples_external_id'), 'samples', ['external_id'], unique=False)
    op.create_index(op.f('ix_samples_status'), 'samples', ['status'], unique=False)
    op.create_table('cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_batch_id', sa.Integer(), nullable=False),
    sa.Column('use_index', sa.Integer(), nullable=False),
    sa.Column('movie_hours', sa.Integer(), nullable=False),
    sa.Column('planned_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['run_batch_id'], ['run_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycles_run_batch_id'), 'cycles', ['run_batch_id'], unique=False)
    op.create_index(op.f('ix_cycles_status'), 'cycles', ['status'], unique=False)
    op.create_table('sample_barcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id', 'barcode', name='uq_sample_barcode')
    )
    op.create_index(op.f('ix_sample_barcodes_barcode'), 'sample_barcodes', ['barcode'], unique=False)
    op.create_index(op.f('ix_sample_barcodes_sample_id'), 'sample_barcodes', ['sample_id'], unique=False)
    op.create_table('cell_uses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('cell_id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('use_index', sa.Integer(), nullable=False),
    sa.Column('well', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cell_uses_cell_id'), 'cell_uses', ['cell_id'], unique=False)
    op.create_index(op.f('ix_cell_uses_cycle_id'), 'cell_uses', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_cell_uses_sample_id'), 'cell_uses', ['sample_id'], unique=False)
    op.create_index(op.f('ix_cell_uses_status'), 'cell_uses', ['status'], unique=False)
    op.create_table('cell_use_barcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cell_use_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['cell_use_id'], ['cell_uses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cell_use_barcodes_barcode'), 'cell_use_barcodes', ['barcode'], unique=False)
    op.create_index(op.f('ix_cell_use_barcodes_cell_use_id'), 'cell_use_barcodes', ['cell_use_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cell_use_barcodes_cell_use_id'), table_name='cell_use_barcodes')
    op.drop_index(op.f('ix_cell_use_barcodes_barcode'), table_name='cell_use_barcodes')
    op.drop_table('cell_use_barcodes')
    op.drop_index(op.f('ix_cell_uses_status'), table_name='cell_uses')
    op.drop_index(op.f('ix_cell_uses_sample_id'), table_name='cell_uses')
    op.drop_index(op.f('ix_cell_uses_cycle_id'), table_name='cell_uses')
    op.drop_index(op.f('ix_cell_uses_cell_id'), table_name='cell_uses')
    op.drop_table('cell_uses')
    op.drop_index(op.f('ix_sample_barcodes_sample_id'), table_name='sample_barcodes')
    op.drop_index(op.f('ix_sample_barcodes_barcode'), table_name='sample_barcodes')
    op.drop_table('sample_barcodes')
    op.drop_index(op.f('ix_cycles_status'), table_name='cycles')
    op.drop_index(op.f('ix_cycles_run_batch_id'), table_name='cycles')
    op.drop_table('cycles')
    op.drop_index(op.f('ix_samples_status'), table_name='samples')
    op.drop_index(op.f('ix_samples_external_id'), table_name='samples')
    op.drop_table('samples')
    op.drop_index(op.f('ix_run_batches_schedule_id'), table_name='run_batches')
    op.drop_index(op.f('ix_run_batches_instrument_id'), table_name='run_batches')
    op.drop_table('run_batches')
    op.drop_index(op.f('ix_schedules_status'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_instruments_serial_number'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_cells_status'), table_name='cells')
    op.drop_index(op.f('ix_cells_code'), table_name='cells')
    op.drop_table('cells')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
